server:
  port: 0

spring:
  application:
    name: transfer-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: transfer-service-${random.value}-
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true

app:
  kafka:
    topics:
      withdraw-money: withdraw-money-topic
      deposit-money: deposit-money-topic
    partitions: 3
    replicas: 3

logging:
  level:
    org.springframework.transaction: TRACE
    org.springframework.kafka.transaction: TRACE
