server:
  port: 0

spring:
  application:
    name: transfer-service

  datasource:
    username: test
    password: test
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: transfer-service-${random.value}-
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true

app:
  kafka:
    topics:
      withdraw-money: withdraw-money-topic
      deposit-money: deposit-money-topic
    partitions: 3
    replicas: 3

logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.apache.kafka.clients.producer.internals.TransactionManager: DEBUG
    org.springframework.kafka.transaction.KafkaAwareTransactionManager: DEBUG

