server:
  port: 0

spring:
  application:
    name: withdrawal-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      isolation-level: read_committed
      properties:
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        group.id: amount-withdrawal-event
        spring.json.trusted.packages: com.github.tennyros.eventmodels.event
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer